### ISSUE TITLE
安装依赖后启动站点失败

### ISSUE THREAD

**Issue by InsHomePgup** [honwhy/shanbay-ext#1]
**问题描述**

pnpm install 以后  pnpm run dev 有一些报错信息并且打不开站点。

![image](https://github.com/user-attachments/assets/0304ce68-6592-4ddf-9b3c-b3f12a1eb82a)

**浏览器信息**
浏览器名称和版本
chrome Version 129.0.6668.100
**其他补充**

**Comment by InsHomePgup** [comment]
node: V20.16.0
pnpm: 9.12.1

**Comment by honwhy** [comment]
试试下面的方案
1、浏览器-插件，打开开发者模式，点击`加载解压缩的扩展`，加载`<rootDir>/.output/chrome-mv3`目录
2、在根目录配置 `web-ext.config.ts` 配置文件，配置浏览器路径
```
// ~/web-ext.config.ts
import { defineRunnerConfig } from 'wxt';

export default defineRunnerConfig({
  binaries: {
    chrome: 'D:/Applications/Scoop/apps/googlechrome/current/chrome.exe', // Use Chrome Beta instead of regular Chrome
    firefox: 'D:/Applications/Scoop/apps/firefox/current/firefox.exe', // Use Firefox Developer Edition instead of regular Firefox
    edge: '/path/to/edge', // Open MS Edge when running "wxt -b edge"
  },
});
```
